# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Backfill < Formula
  desc "Get paid while long CLI commands and coding agents run"
  homepage "https://backfill.sh"
  version "0.8.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shyamsivakumar/backfill/releases/download/v0.8.7/backfill_darwin_amd64.tar.gz"
      sha256 "868d2016d4ab7f5283a6b00809a0bb57f6c480db27dd8a341d630e33396a8d3f"

      define_method(:install) do
        bin.install "bf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shyamsivakumar/backfill/releases/download/v0.8.7/backfill_darwin_arm64.tar.gz"
      sha256 "717e42dbf253d8099304363c413dbc1fab02cff04a2ae873a90c16a75c2b9a2f"

      define_method(:install) do
        bin.install "bf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shyamsivakumar/backfill/releases/download/v0.8.7/backfill_linux_amd64.tar.gz"
      sha256 "fba4efdf19a3161ca1ac1e5967df657e74d6d630b4a0495f025e3d18756042aa"
      define_method(:install) do
        bin.install "bf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shyamsivakumar/backfill/releases/download/v0.8.7/backfill_linux_arm64.tar.gz"
      sha256 "8d8d3d0150199d361fef2ccbb3c52edb351323e1c2b0cf380580a36f01fa81d4"
      define_method(:install) do
        bin.install "bf"
      end
    end
  end
end
