# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Backfill < Formula
  desc "Get paid while long CLI commands and coding agents run"
  homepage "https://backfill.sh"
  version "0.8.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shyamsivakumar/backfill/releases/download/v0.8.12/backfill_darwin_amd64.tar.gz"
      sha256 "d4c8fda510df36cf3125f027f7ab61b767902df82212e7d6cf70cfa5f52e9ef1"

      define_method(:install) do
        bin.install "bf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shyamsivakumar/backfill/releases/download/v0.8.12/backfill_darwin_arm64.tar.gz"
      sha256 "401f1c614cc0713134b6976dbec33ef1a762c4fc4a26b8547d387aefafd70a43"

      define_method(:install) do
        bin.install "bf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shyamsivakumar/backfill/releases/download/v0.8.12/backfill_linux_amd64.tar.gz"
      sha256 "a4ba81121713064f1b40cb0dbc1b1cf6c3d109bc5ba7f3e6afb6171e9f3584d9"
      define_method(:install) do
        bin.install "bf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shyamsivakumar/backfill/releases/download/v0.8.12/backfill_linux_arm64.tar.gz"
      sha256 "26a93fd5ee1de9a2a801fd1d623577bb85dc4e9a529bab7f4769af6223236233"
      define_method(:install) do
        bin.install "bf"
      end
    end
  end
end
